### ISSUE TITLE
能否加入采集评论功能？

### ISSUE THREAD

**Issue by Cregin** [xueshanlinghu/zsxq_to_pdf#1]
把评论也写入到pdf中，另外再把css美化一下就很完美了，谢谢

**Comment by Cregin** [comment]
html文件过多时无法生成pdf  Error: Failed to load file:///Users/macOS/Downloads/zsxq_to_pdf-master/313.html, with network status code 201 and http status code 0 - Error opening /Users/macOS/Downloads/zsxq_to_pdf-master/313.html: Too many open files

**Comment by xueshanlinghu** [comment]
> html文件过多时无法生成pdf Error: Failed to load file:///Users/macOS/Downloads/zsxq_to_pdf-master/313.html, with network status code 201 and http status code 0 - Error opening /Users/macOS/Downloads/zsxq_to_pdf-master/313.html: Too many open files

我试过文件名路径过长的时候无法生成，文件过多没有试过，不知道你单个文件多大，我试过有两千多个文件编号依然成功生成的就是略慢。这块我也不是特别了解，帮不到你。

**Comment by xueshanlinghu** [comment]
> 把评论也写入到pdf中，另外再把css美化一下就很完美了，谢谢

如果您会 css 的话麻烦帮忙调整提交 PR，我也用的是前人写的 css，暂时满足我的个人需求。

**Comment by xueshanlinghu** [comment]
@lzyroot 至于加入采集评论的功能，我主要是需要星主的内容来学习，个人暂时没有评论采集的需求，不过你可以根据你的需要增加，提交 PR。

**Comment by xueshanlinghu** [comment]
朋友没有进一步的回复了，这边关闭该 Issue 了。
